[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "scripts"

# See more config options https://github.com/foundry-rs/foundry/blob/master/config/README.md

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

